spring:
    application:
        name: imap-service
    datasource:
        url: jdbc:mysql://localhost:3306/mail-db
        username: root
        password: mailbox
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
server:
    port: 8081
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs
userservice:
    url: http://localhost:8082
