spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
  config:
    import: optional:file:C:\Users\асус\IdeaProjects\microservices\email-moicroservices\api-gateway\src\main\resources\.env[.properties]
  application:
    name: smtp-service
  datasource:
    url: jdbc:mysql://localhost:3306/mail-db
    username: root
    password: mailbox
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8083
  tomcat:
    max-swallow-size: 100MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
service:
  user-service-url: ${USER_SERVICE_URL}
google-client:
  id: ${GOOGLE_CLIENT_ID}
  secret: ${GOOGLE_CLIENT_SECRET}
  callback-uri: http://67.207.79.91.nip.io:9090/api/v1/users
encryption:
  secret: ${ENCRYPTION_SECRET}
bucket:
  name: ${AWS_BUCKET}



