spring:
  config:
    import: optional:file:C:\Users\асус\IdeaProjects\microservices\email-moicroservices\api-gateway\src\main\resources\.env[.properties]
  application:
    name: smtp-service
  datasource:
    url: jdbc:mysql://localhost:3306/mail-db
    username: root
    password: mailbox
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8083
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
service:
  user-service-url: ${USER_SERVICE_URL}
google-client:
  id: ${GOOGLE_CLIENT_ID}
  secret: ${GOOGLE_CLIENT_SECRET}


