spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/mail-db
    username: root
    password: mailbox
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"