spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/mail-db
    username: root
    password: mailbox
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082

jwt:
  secret: "bQeThWmZq4t7w!z$C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdSgVkYp3s6v9y$B&E)"
  issuer: "email-ms"
