spring:
  config:
    import: optional:file:C:\Users\асус\IdeaProjects\microservices\email-moicroservices\api-gateway\src\main\resources\.env[.properties]
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/mail-db
    username: root
    password: mailbox
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
jwt:
  secret: "bQeThWmZq4t7w!z$C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdSgVkYp3s6v9y$B&E)"
  issuer: "email-ms"
service:
  imap-service-url: ${IMAP_SERVICE_URL}
  smtp-service-url: ${SMTP_SERVICE_URL}
