spring:
  application:
    name: api-gateway

server:
  port: 9090
debug: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /aggregate/user-service/api-docs
      - name: imap-service
        url: /aggregate/imap-service/api-docs
      - name: smtp-service
        url: /aggregate/smtp-service/api-docs
  api-docs:
    path: /api-docs
service:
  user-service-url: ${USER_SERVICE_URL}
  imap-service-url: ${IMAP_SERVICE_URL}
  smtp-service-url: ${SMTP_SERVICE_URL}


