spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: smtp-service
          uri: lb://smtp-service
          predicates:
            - Path=/api/v1/email/**
        - id: user-controller
          uri: lb://user-service
          predicates:
           - Path=/api/v1/users/**
        - id: auth-controller
          uri: lb://user-service
          predicates:
           - Path=/api/v1/auth/**
        - id: imap-controller
          uri: lb://imap
          predicates:
            - Path=/api/v1/read/**
        - id: folder-controller
          uri: lb://imap
          predicates:
            - Path=/api/v1/folder/**
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
server:
  port: 9090
