apiVersion: apps/v1
kind: Deployment
metadata:
  name: imap-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imap-service
  template:
    metadata:
      labels:
        app: imap-service
    spec:
      containers:
        - name: imap-service
          image: artamonovdima/imap:latest
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: imap-service-config
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                    key: USER_SERVICE_URL
                    name: common-config
            - name: ENCRYPTION_SECRET
              valueFrom:
                secretKeyRef:
                  name: imap-secrets
                  key: ENCRYPTION_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: imap-service
spec:
  selector:
    app: imap-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: imap-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.default.svc.cluster.local:3306/mail-db"
---
apiVersion: v1
kind: Secret
metadata:
  name: imap-secrets
type: Opaque
data:
  ENCRYPTION_SECRET: dVFBeFlrOU9sS25IN2RHZlZKV0ZnVHdZVHI1OXZSSWdmMU8ybzEyS2JURT0=
