apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp-service
  template:
    metadata:
      labels:
        app: smtp-service
    spec:
      containers:
        - name: smtp-service
          image: artamonovdima/smtp:latest
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: smtp-service-config
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: USER_SERVICE_URL
                  name: common-config
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: AWS_SECRET_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: AWS_REGION
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: AWS_BUCKET
            - name: ENCRYPTION_SECRET
              valueFrom:
                secretKeyRef:
                  name: smtp-secrets
                  key: ENCRYPTION_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: smtp-service
spec:
  selector:
    app: smtp-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.default.svc.cluster.local:3306/mail-db"
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secrets
type: Opaque
data:
  GOOGLE_CLIENT_ID: <define-your-credentials>
  GOOGLE_CLIENT_SECRET: <define-your-credentials>
  AWS_ACCESS_KEY: <define-your-credentials>
  AWS_BUCKET: <define-your-credentials>
  AWS_REGION: <define-your-credentials>
  AWS_SECRET_KEY: <define-your-credentials>
  ENCRYPTION_SECRET: dVFBeFlrOU9sS25IN2RHZlZKV0ZnVHdZVHI1OXZSSWdmMU8ybzEyS2JURT0=

